#!/bin/bash
cd bin
#cp data/touchcalib/params.txt /tmp/touchparams.txt
#cp data/touchcalib/params_tanbeats.bak data/touchcalib/params.txt
./tox music $@ --fullscreen
#cp /tmp/touchparams.txt data/touchcalib/params.txt
cd ..
